"""Jokes/quotes/riddles/trivia (Section 6B)
Auto-split from the original single-file chatbot.py - see main.py for load order.
"""

# SECTION 6B: FUN EXTRAS (jokes, quotes, riddles, trivia)
# ==============================================================================

class FunExtras:
    """
    A bank of hand-written, hard-coded fun content: jokes, quotes,
    riddles (with answers, tracked per-session so the bot can reveal them
    on request), and trivia questions (with multiple choice + answer
    checking). Everything here is fixed content selected at random -
    no generation, no external API calls, no learning.
    """

    # Restructured into {"en": [...], "sw": [...], "fr": [...]} so jokes can
    # be told in whichever language LanguageDetector identified, same idea
    # as the Section 8 response banks. IMPORTANT NOTE ON TRANSLATION: most
    # of the English jokes below are wordplay puns ("Windows" the OS vs. a
    # window, "cache"/"close by", "C"/"see") that simply don't have a
    # matching pun in Swahili or French - translating them literally would
    # just produce a confusing, unfunny sentence. So instead of a forced
    # line-for-line translation, the "sw" and "fr" lists are a smaller,
    # separately curated set: jokes that DO translate cleanly (or have a
    # natural equivalent pun in that language) were translated, and the
    # untranslatable puns were swapped for a different, comparably silly
    # joke actually written in that language.
    JOKES = {
        "en": [
        ("Why do programmers prefer dark mode?", "Because light attracts bugs."),
        ("Why did the function break up with the loop?", "It felt like it kept going in circles."),
        ("Why was the math book sad?", "It had too many problems."),
        ("Why don't scientists trust atoms?", "Because they make up everything."),
        ("Why did the scarecrow win an award?", "Because he was outstanding in his field."),
        ("What do you call a fish with no eyes?", "A fsh."),
        ("Why can't you give Elsa a balloon?", "She'll let it go."),
        ("How does a computer get drunk?", "It takes screenshots."),
        ("Why did the developer go broke?", "Because they used up all their cache."),
        ("What's a chatbot's favorite type of music?", "Algo-rhythms."),
        ("Why did the chatbot go to therapy?", "It had too many unresolved exceptions."),
        ("Why was the JavaScript developer sad?", "Because they didn't Node how to Express their feelings."),
        ("What did the database say to the other database?", "I think we should table this discussion."),
        ("Why did the programmer quit their job?", "They didn't get arrays."),
        ("How do you comfort a JavaScript bug?", "You console it."),
        ("Why do Python programmers wear glasses?", "Because they can't C."),
        ("Why did the programmer go outside?", "Because they heard about the great outdoors' UI."),
        ("What's the object-oriented way to become wealthy?", "Inheritance."),
        ("Why do programmers hate nature?", "It has too many bugs and no debugger."),
        ("What do you call eight hobbits?", "A hobbyte."),
        ("Why did the SQL query go to therapy?", "It had too many joins to sort out."),
        ("Why was the computer cold?", "It left its Windows open."),
        ("What's a chatbot's favorite dance?", "The algo-rithm."),
        ("Why did the recursion function go to jail?", "It kept calling itself."),
        ("How do robots eat guacamole?", "With computer chips."),
        ("What did the router say to the doctor?", "It hurts when IP."),
        ("Why did the programmer bring a ladder to work?", "To reach the high-level languages."),
        ("Why was the array so calm?", "It had everything in order."),
        ("What do you call a programmer from Finland?", "Nerdic."),
        ("Why did the developer name their child 'Cache'?", "So they'd always be close by."),
        ("Why did the algorithm break up with the dataset?", "It just wasn't a good fit."),
        ("What do you call a bear with no teeth?", "A gummy bear."),
        ("Why did the bicycle fall over?", "It was two tired."),
        ("What do you call cheese that isn't yours?", "Nacho cheese."),
        ("Why did the coffee file a police report?", "It got mugged."),
        ("What do you call a fake noodle?", "An impasta."),
        ("Why did the golfer bring two pairs of pants?", "In case they got a hole in one."),
        ("What do you call a can opener that doesn't work?", "A can't opener."),
        ("Why did the tomato turn red?", "Because it saw the salad dressing."),
        ("What do you call a dinosaur that crashes their car?", "Tyrannosaurus wrecks."),
        ("Why can't you trust stairs?", "They're always up to something."),
        ("What do you call an alligator in a vest?", "An investigator."),
        ("Why did the cookie go to the doctor?", "It was feeling crummy."),
        ("What did one wall say to the other?", "I'll meet you at the corner."),
        ("Why don't eggs tell jokes?", "They'd crack each other up."),
        ("What do you call a sleeping dinosaur?", "A dino-snore."),
        ("Why did the music teacher get locked out of the classroom?", "Because their keys were on the piano."),
        ("What's orange and sounds like a parrot?", "A carrot."),
        ("Why did the scarecrow become a motivational speaker?", "He was outstanding in every field he entered."),
        ("Why did the smartphone break up with the tablet?", "It felt they were on different planes."),
        ("What do you call a snowman with a six-pack?", "An abdominal snowman."),
        ("Why did the gym close down?", "It just didn't work out."),
        ("What do you call a fish wearing a bowtie?", "So-fish-ticated."),
        ("Why did the picture go to jail?", "It was framed."),
        ("What do you call a boomerang that won't come back?", "A stick."),
        ("Why did the stadium get hot after the game?", "All the fans left."),
        ("What do you call a pile of cats?", "A meow-ntain."),
        ("Why did the belt get arrested?", "For holding up a pair of pants."),
        ("What do you call a very small valentine?", "A valen-tiny."),
        ("Why did the melon jump into the lake?", "It wanted to be a watermelon."),
        ("What did the ocean say to the shore?", "Nothing, it just waved."),
        ("Why did the bicycle need a kickstand?", "It was two tired to stand alone."),
        ("What do you call a laughing motorcycle?", "A Yamaha-ha-ha."),
        ("Why did the mushroom get invited to every party?", "Because he was a fungi."),
        ("What did the janitor say when he jumped out of the closet?", "Supplies!"),
        ("Why do seagulls fly over the sea?", "Because if they flew over the bay they'd be bagels."),
        ("What do you call a bear caught in the rain?", "A drizzly bear."),
        ("How does the moon cut his hair?", "Eclipse it."),
        ("What did the grape say when it got stepped on?", "Nothing, it just let out a little wine."),
        ("Why did the traffic light turn red?", "You would too if you had to change in the middle of the street."),
        ("Why don't oysters share their pearls?", "Because they're shellfish."),
        ("What do you call a dog magician?", "A labracadabrador."),
        ("Why did the coffee cup file a complaint?", "It felt mugged twice in the same joke bank."),
        ("What do you call a factory worker who makes exceptional jokes?", "A pun-cher operator."),
        ("Why did the chatbot cross the road?", "To optimize its route to the other side."),
        ("What do you call two robots who fall in love?", "A perfect match, byte for byte."),
        ("Why did the smartphone go to therapy?", "It had too many unresolved notifications."),
        ("Why did the semicolon break up with the comma?", "It felt the relationship needed a full stop."),
        ("What did the terminal say to the programmer?", "Let's not have any more exceptions between us."),
        ("Why did the spreadsheet apply for a job?", "It wanted to make the cut."),
        ("What do you call a very polite robot?", "R-U-decent."),
        ("Why did the compiler stay calm?", "It knew how to handle exceptions gracefully."),
        ("What do you call an owl who does magic tricks?", "Hoo-dini."),
        ("Why did the smartphone need glasses?", "It lost all its contacts."),
        ("What do you call a factory that makes okay products?", "A satisfactory."),
        ("Why did the calendar feel popular?", "It always had a lot of dates."),
        ("What do you call a group of chatbots on a call?", "A conference of responses."),
        ("Why did the WiFi break up with the ethernet cable?", "It needed some space."),
        ("What do you call a robot that takes the scenic route?", "A round-about-bot."),
        ("Why did the tablet go to the doctor?", "It had a virus and lost its apps-etite."),
        ("What do you call a pig that does karate?", "A pork chop."),
        ("Why don't skeletons fight each other?", "They don't have the guts."),
        ("What do you call a fish that needs help with vocals?", "Auto-tuna."),
        ("Why did the golfer bring an extra pair of socks?", "In case he got a hole in one."),
        ("What do you call a dinosaur with an extensive vocabulary?", "A thesaurus."),
        ("Why did the computer keep freezing?", "It left its Windows open in winter."),
        ("What do you call a nervous javelin thrower?", "Shakespeare."),
        ("Why did the banana go to the doctor?", "It wasn't peeling well."),
        ("What do you call an ant who fights crime?", "A vigilANTe."),
        ("Why did the student eat his homework?", "Because the teacher said it was a piece of cake."),
        ("What do you call a group of disorganized cats?", "A cat-astrophe."),
        ("Why did the barber win the race?", "He knew a shortcut."),
        ("What do you call a fish with two knees?", "A two-knee fish (tuna fish)."),
        ("Why did the picture frame get a promotion?", "It always knew how to stay well-adjusted."),
        ("What do you call a snowman in July?", "A puddle."),
        ("What do you call a very sad cup of coffee?", "A depresso."),
        ("Why did the light bulb fail the test?", "It wasn't that bright to begin with."),
        ("What do you call a nosy pepper?", "Jalapeño business."),
        ("Why did the orange stop rolling down the hill?", "It ran out of juice."),
        ("What do you call a bear with no ears?", "B."),
        ("What do you call a can opener that finally works?", "A relief."),
        ("Why do bees have sticky hair?", "Because they use honeycombs."),
        ("What's the best thing about Switzerland?", "I don't know, but the flag is a big plus."),
        ("Why did the tomato blush?", "Because it saw the salad dressing again."),
        ("What do you call a factory that sells passable products?", "A satisfactory."),
        ("Why did the calculator break up with the abacus?", "It felt the relationship didn't add up."),
        ("What did the password say to the hacker?", "You shall not guess."),
        ("Why did the router go to therapy?", "It had too many connection issues."),
        ("What do you call a bear stuck in the rain with no shelter?", "A drizzly bear."),
        ("Why did the app crash before the interview?", "It had too many unresolved dependencies."),
        ("What do you call a musical laptop?", "A Dell-ta blues machine."),
        ("Why did the developer refuse to leave the party?", "They were still waiting for a callback."),
        ("What do you call a spider that just graduated?", "A web developer."),
        ("Why did the smartphone bring a sweater?", "It heard it might get a little cold storage."),
        ("What do you call a group of musical whales?", "An orca-stra."),
        ("Why did the flashcard feel confident?", "It had been reviewed enough times to reach box five."),
        ("What do you call a very organized password?", "Well-hashed."),
        ("Why did the topic tracker never get lost?", "It always remembered where the conversation had been."),
        ("What do you call a calculator that only whispers?", "A soft-ware."),
        ("Why did the unit converter feel so well-rounded?", "It could see things from every angle, metric or not."),
        ("What did the CNN say to the blurry photo?", "Let's work on your resolution."),
        ("Why did the transformer model bring an umbrella?", "It heard there was a chance of gradient descent."),
        ("Why did the flashcard box system get promoted?", "It always knew when to move things up."),
        ("What do you call a chatbot that tells too many puns?", "A repeat pun-der."),
        ("Why did the password generator refuse to relax?", "It took its entropy very seriously."),
        ("Why did the scientific calculator stay calm under pressure?", "It always knew the log-ical next step."),
        ("What do you call a leitner box that's overly competitive?", "Box-ambitious."),
        ("Why did the flashcard app apologize?", "It kept bringing up the same old cards."),
        ("What do you call a CNN that tells jokes?", "A pun-volutional neural network."),
        ("Why don't calendars ever get stressed?", "Their days are always numbered anyway."),
        ("What do you call a snowman with a great sense of humor?", "Frosty the pun-man."),
        ("Why did the GPU apply for a comedy show?", "It had great parallel processing for punchlines."),
        ("What do you call a dictionary that tells jokes?", "A pun-thology."),
        ("Why did the flashcard blush?", "It got moved up a box in front of everyone."),
        ("What's a topic tracker's favorite dance move?", "The callback."),
        ("Why did the API rate limit apologize?", "It just needed everyone to slow down a little."),
        ("Why did the Leitner box system win an award?", "It always knew how to manage its priorities."),
        ("What do you call a password with excellent taste?", "Sophisti-hashed."),
        ("Why did the scientific calculator never lie?", "It always gave you the real logarithm."),
        ("What do you call a spreadsheet that tells dad jokes?", "A cell-ebration of puns."),
        ("Why did the query optimizer get promoted?", "It always found the fastest path to the punchline."),
        ],
        "sw": [
            ("Kwa nini kompyuta ilikuwa baridi?", "Iliacha Windows (madirisha) yake wazi."),
            ("Kwa nini paka hakupenda kompyuta?", "Aliogopa kipanya."),
            ("Mwalimu aliuliza mtoto ni nani aliyegundua Amerika. Mtoto akajibu:", "Sikuwepo pale, nawezaje kujua?"),
            ("Kwa nini kitabu cha hesabu kilikuwa na huzuni?", "Kilikuwa na matatizo mengi sana."),
            ("Kwa nini punda alikataa kusoma gazeti?", "Aliambiwa habari zote zilikuwa za punda mwenzake."),
            ("Simu iliuliza chaja yake, unanipenda kweli?", "Chaja ikajibu, ndiyo maana ninakuunganisha kila siku."),
            ("Kwa nini simba hakushiriki mashindano ya mbio?", "Alisema kukimbiza ndiyo kazi yake, si kukimbia."),
            ("Kwa nini mnyama wa pweza hachelewi kazini?", "Ana mikono minane ya kufanyia kazi."),
            ("Kwa nini programu ilikwenda kwa mtaalamu wa akili?", "Ilikuwa na hitilafu nyingi ambazo hazijatatuliwa."),
            ("Rafiki mmoja alimwuliza mwenzake, kwa nini una miwani?", "Alijibu, ili nione mambo wazi zaidi, si kwa mtindo."),
            ("Kwa nini kuku alivuka barabara?", "Ili afike upande wa pili tu."),
            ("Kwa nini mvuvi hakuwahi kukosa samaki?", "Alijua kila hila ya kuvua."),
            ("Baba aliuliza mwanawe, kwa nini anga ni bluu?", "Mwanawe akajibu, labda kwa sababu bahari inapenda kujionyesha juu."),
            ("Kwa nini mlima haukatai wageni?", "Kwa sababu una nafasi ya kutosha kwa kila mtu."),
            ("Kwa nini simu mahiri ilipendwa na kila mtu?", "Ilijua kuunganisha watu wote pamoja."),
            ("Mtoto aliuliza mama yake, chai inapendaje kelele?", "Mama akajibu, huwa haipendi - ndiyo maana huwa kimya ikichemka polepole."),
            ("Kwa nini gari halijui kuogelea?", "Halikuwahi kufundishwa - magurudumu yake ni ya barabarani tu."),
            ("Kwa nini kalenda ilikuwa maarufu?", "Ilikuwa na tarehe nyingi za kukumbukwa kila mwezi."),
            ("Rafiki mmoja aliuliza, kwa nini radio haiwezi kuona?", "Kwa sababu inasikia tu, haioni."),
            ("Kwa nini mkulima alikuwa mwenye furaha kila siku?", "Alijua kila mbegu ana siku yake ya kuota."),
            ("Kwa nini mwalimu alibeba tochi darasani?", "Ili aonyeshe wanafunzi njia sahihi ya kufikiri."),
            ("Kwa nini mbwa hakuweza kusoma gazeti?", "Alikuwa na hamu zaidi ya kunusa habari kuliko kuzisoma."),
            ("Mtoto aliuliza baba, kwa nini nyota zinameremeta?", "Baba akajibu, zinafurahi kutuona chini tukiwatazama."),
            ("Kwa nini mvua ilichelewa siku ile?", "Ilikuwa ikingoja wingu sahihi la kuandamana nalo."),
            ("Kwa nini mlinzi wa mlango alikuwa mkarimu?", "Alijua kila mgeni anahitaji kukaribishwa vizuri."),
            ("Buda aliuliza simu yake, wewe ni fiti?", "Simu ikajibu, poa tu, battery pekee ndio noma."),
            ("Msee mmoja aliuliza rafiki yake, story yako ni gani leo?", "Akajibu, ni ile ya kawaida, freshi tu bila ganji."),
            ("Kwa nini keyboard ilikataa ku-type?", "Ilisema iko na noma na ile space bar, imechoka."),
        ],
        "fr": [
            ("Pourquoi l'ordinateur avait-il froid ?", "Il avait laissé ses fenêtres (Windows) ouvertes."),
            ("Pourquoi le chat n'aimait-il pas l'ordinateur ?", "Il avait peur de la souris."),
            ("Pourquoi le livre de maths était-il triste ?", "Il avait trop de problèmes."),
            ("Que dit un escargot quand il croise une limace ?", "Regarde, un escargot sans maison !"),
            ("Pourquoi le squelette n'allait-il jamais à la fête ?", "Il n'avait personne avec qui danser, il manquait de corps."),
            ("Pourquoi les poissons détestent-ils le tennis ?", "Ils ont peur du filet."),
            ("Que fait une fraise quand elle voit une autre fraise ?", "Rien, elles se fondent juste dans la même confiture."),
            ("Pourquoi l'ordinateur est-il allé chez le médecin ?", "Il avait attrapé un virus."),
            ("Qu'est-ce qu'un crocodile qui surveille tout ?", "Un inspecteur des eaux."),
            ("Pourquoi le café a-t-il porté plainte ?", "Il s'est fait vider trop vite chaque matin."),
            ("Que dit un informaticien fatigué le matin ?", "J'ai besoin d'un redémarrage complet."),
            ("Pourquoi la lumière n'entre-t-elle jamais dans un bar ?", "Elle risquait de créer une interférence."),
            ("Pourquoi le robot est-il retourné à l'école ?", "Pour améliorer son intelligence artificielle."),
            ("Que dit un chien programmeur ?", "Woof, mon code aboie mais il fonctionne."),
            ("Pourquoi la voiture ne pouvait-elle pas nager ?", "Elle n'avait que des roues, pas de nageoires."),
            ("Que fait une pomme de terre en vacances ?", "Elle se prélasse au soleil jusqu'à devenir frite."),
            ("Pourquoi le facteur était-il toujours de bonne humeur ?", "Il aimait distribuer de bonnes nouvelles chaque jour."),
            ("Pourquoi le calendrier était-il si populaire ?", "Il avait toujours plein de dates à proposer."),
            ("Que dit une horloge quand elle a faim ?", "Elle revient à midi, sans faute."),
            ("Pourquoi le fermier était-il toujours joyeux ?", "Chaque graine avait son propre jour pour germer."),
        ],
    }


    QUOTES = [
        ("The only way to do great work is to love what you do.", "Steve Jobs"),
        ("In the middle of difficulty lies opportunity.", "Albert Einstein"),
        ("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
        ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
        ("Simplicity is the soul of efficiency.", "Austin Freeman"),
        ("Code is like humor. When you have to explain it, it's bad.", "Cory House"),
        ("First, solve the problem. Then, write the code.", "John Johnson"),
        ("The best error message is the one that never shows up.", "Thomas Fuchs"),
        ("Programs must be written for people to read, and only incidentally for machines to execute.", "Harold Abelson"),
        ("Talk is cheap. Show me the code.", "Linus Torvalds"),
        ("Whether you think you can or think you can't, you're right.", "Henry Ford"),
        ("The journey of a thousand miles begins with a single step.", "Lao Tzu"),
        ("Do not wait to strike till the iron is hot, but make it hot by striking.", "William Butler Yeats"),
        ("The best way to predict the future is to invent it.", "Alan Kay"),
        ("It always seems impossible until it's done.", "Nelson Mandela"),
        ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
        ("What we think, we become.", "Buddha"),
        ("The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"),
        ("Believe you can and you're halfway there.", "Theodore Roosevelt"),
        ("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
        ("Not all those who wander are lost.", "J.R.R. Tolkien"),
        ("The only true wisdom is in knowing you know nothing.", "Socrates"),
        ("A room without books is like a body without a soul.", "Cicero"),
        ("Turn your wounds into wisdom.", "Oprah Winfrey"),
        ("Perfection is not attainable, but if we chase perfection we can catch excellence.", "Vince Lombardi"),
        ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
        ("The mind is everything. What you think you become.", "Buddha"),
        ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
        ("Everything you've ever wanted is on the other side of fear.", "George Addair"),
        ("Act as if what you do makes a difference. It does.", "William James"),
        ("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
        ("Whether you think you can, or think you can't, you're right.", "Henry Ford"),
        ("Good code is its own best documentation.", "Steve McConnell"),
        ("Deleted code is debugged code.", "Jeff Sickel"),
        ("Premature optimization is the root of all evil.", "Donald Knuth"),
        ("Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "Martin Fowler"),
        ("Make it work, make it right, make it fast.", "Kent Beck"),
        ("It's not a bug, it's an undocumented feature.", "Anonymous"),
        ("The best error message is the one that never shows up.", "Thomas Fuchs"),
        ("Testing leads to failure, and failure leads to understanding.", "Burt Rutan"),
        ("Programs are meant to be read by humans and only incidentally for computers to execute.", "Donald Knuth"),
        ("The trouble with programmers is that you can never tell what a programmer is doing until it's too late.", "Seymour Cray"),
        ("Life is what happens when you're busy making other plans.", "John Lennon"),
        ("The unexamined life is not worth living.", "Socrates"),
        ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
        ("Out of clutter, find simplicity.", "Albert Einstein"),
        ("The only way to have a friend is to be one.", "Ralph Waldo Emerson"),
        ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
        ("Everything has beauty, but not everyone sees it.", "Confucius"),
        ("To live is the rarest thing in the world. Most people exist, that is all.", "Oscar Wilde"),
        ("Well done is better than well said.", "Benjamin Franklin"),
        ("Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.", "Mark Twain"),
        ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
        ("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"),
        ("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
        ("Learning never exhausts the mind.", "Leonardo da Vinci"),
        ("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown Jr."),
        ("Little things make big days.", "Isabel Marant"),
        ("If you want to lift yourself up, lift up someone else.", "Booker T. Washington"),
        ("Keep your face always toward the sunshine, and shadows will fall behind you.", "Walt Whitman"),
        ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
        ("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
        ("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
        ("The struggle you're in today is developing the strength you need for tomorrow.", "Robert Tew"),
        ("Difficult roads often lead to beautiful destinations.", "Zig Ziglar"),
        ("Do what you love and success will follow.", "Anonymous"),
        ("Push yourself, because no one else is going to do it for you.", "Anonymous"),
        ("Great things never come from comfort zones.", "Anonymous"),
        ("Dream it. Wish it. Do it.", "Anonymous"),
        ("Success doesn't just find you. You have to go out and get it.", "Anonymous"),
        ("The harder you work for something, the greater you'll feel when you achieve it.", "Anonymous"),
        ("Dream bigger. Do bigger.", "Anonymous"),
        ("Don't stop when you're tired. Stop when you're done.", "Anonymous"),
        ("Wake up with determination. Go to bed with satisfaction.", "Anonymous"),
        ("Do something today that your future self will thank you for.", "Sean Patrick Flanery"),
        ("Little things make big days.", "Isabel Marant"),
        ("It's going to be hard, but hard does not mean impossible.", "Anonymous"),
        ("Don't wait for opportunity. Create it.", "Anonymous"),
        ("Sometimes we're tested not to show our weaknesses, but to discover our strengths.", "Anonymous"),
        ("The key to success is to focus on goals, not obstacles.", "Anonymous"),
        ("A year from now you may wish you had started today.", "Karen Lamb"),
        ("The expert in anything was once a beginner.", "Helen Hayes"),
        ("There is no elevator to success, you have to take the stairs.", "Anonymous"),
        ("Don't limit your challenges, challenge your limits.", "Anonymous"),
        ("Fall seven times, stand up eight.", "Japanese Proverb"),
        ("What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"),
        ("The distance between dreams and reality is called action.", "Anonymous"),
        ("You don't have to be great to start, but you have to start to be great.", "Zig Ziglar"),
        ("A little progress each day adds up to big results.", "Anonymous"),
        ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
        ("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"),
        ("Whatever you are, be a good one.", "Abraham Lincoln"),
        ("Try to be a rainbow in someone's cloud.", "Maya Angelou"),
        ("In the middle of difficulty lies opportunity.", "Albert Einstein"),
        ("It is never too late to be what you might have been.", "George Eliot"),
        ("Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"),
        ("Be yourself; everyone else is already taken.", "Oscar Wilde"),
        ("The only impossible journey is the one you never begin.", "Tony Robbins"),
        ("In this life we cannot do great things. We can only do small things with great love.", "Mother Teresa"),
        ("It always seems impossible until it's done.", "Nelson Mandela"),
        ("Believe in yourself and all that you are.", "Christian D. Larson"),
        ("You are braver than you believe, stronger than you seem, and smarter than you think.", "A.A. Milne"),
        ("Everything you can imagine is real.", "Pablo Picasso"),
        ("The only source of knowledge is experience.", "Albert Einstein"),
        ("Logic will get you from A to B. Imagination will take you everywhere.", "Albert Einstein"),
        ("The best revenge is massive success.", "Frank Sinatra"),
        ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
        ("If you can dream it, you can do it.", "Walt Disney"),
        ("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
        ("The mind is not a vessel to be filled but a fire to be kindled.", "Plutarch"),
        ("He who has a why to live can bear almost any how.", "Friedrich Nietzsche"),
        ("Simplicity is the soul of efficiency.", "Austin Freeman"),
        ("Knowing yourself is the beginning of all wisdom.", "Aristotle"),
        ("The journey of a thousand miles begins with a single step.", "Lao Tzu"),
        ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
        ("Happiness depends upon ourselves.", "Aristotle"),
        ("The unexamined life is not worth living.", "Socrates"),
        ("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
        ("Only those who dare to fail greatly can ever achieve greatly.", "Robert F. Kennedy"),
        ("The mind that opens to a new idea never returns to its original size.", "Albert Einstein"),
        ("What we achieve inwardly will change outer reality.", "Plutarch"),
        ("Turn your face to the sun and the shadows fall behind you.", "Maori Proverb"),
        ("The best way out is always through.", "Robert Frost"),
        ("Courage is not the absence of fear, but the triumph over it.", "Nelson Mandela"),
        ("Nothing is impossible, the word itself says 'I'm possible'.", "Audrey Hepburn"),
        ("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
        ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
        ("Opportunities don't happen. You create them.", "Chris Grosser"),
        ("Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"),
        ("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"),
    ]

    RIDDLES = [
        ("What has keys but no locks, space but no room, and you can enter but not go in?", "a keyboard"),
        ("What gets wetter the more it dries?", "a towel"),
        ("I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", "an echo"),
        ("The more you take, the more you leave behind. What am I?", "footsteps"),
        ("What has a head and a tail but no body?", "a coin"),
        ("What can travel around the world while staying in a corner?", "a stamp"),
        ("What has to be broken before you can use it?", "an egg"),
        ("I'm tall when I'm young and short when I'm old. What am I?", "a candle"),
        ("What has many teeth but cannot bite?", "a comb"),
        ("What goes up but never comes down?", "your age"),
        ("What can you catch but not throw?", "a cold"),
        ("What has a neck but no head?", "a bottle"),
        ("What has hands but cannot clap?", "a clock"),
        ("What is full of holes but still holds water?", "a sponge"),
        ("What can fill a room but takes up no space?", "light"),
        ("What has one eye but cannot see?", "a needle"),
        ("What building has the most stories?", "a library"),
        ("What is always in front of you but can't be seen?", "the future"),
        ("What kind of room has no doors or windows?", "a mushroom"),
        ("What runs but never walks, has a mouth but never talks?", "a river"),
        ("What has a thumb and four fingers but is not alive?", "a glove"),
        ("The more of this there is, the less you see. What is it?", "darkness"),
        ("What word becomes shorter when you add two letters to it?", "short"),
        ("What can you break without touching it?", "a promise"),
        ("What has legs but doesn't walk?", "a table"),
        ("What has a bottom at the top?", "your legs"),
        ("What five-letter word becomes shorter when you add two letters to it?", "short"),
        ("I am not alive, but I grow. I don't have lungs, but I need air. What am I?", "fire"),
        ("What comes once in a minute, twice in a moment, but never in a thousand years?", "the letter m"),
        ("What can you keep after giving it to someone?", "your word"),
        ("The person who makes it, sells it. The person who buys it never uses it. What is it?", "a coffin"),
        ("What has many rings but no fingers?", "a tree"),
        ("What goes through cities and fields but never moves?", "a road"),
        ("What has a face and two hands but no arms or legs?", "a clock"),
        ("What can travel all around the globe without leaving its corner?", "a stamp"),
        ("What has words but never speaks?", "a book"),
        ("What is so fragile that saying its name breaks it?", "silence"),
        ("What has a spine but no bones?", "a book"),
        ("What has an eye but cannot see?", "a hurricane"),
        ("What invention lets you look right through a wall?", "a window"),
        ("What kind of tree can you carry in your hand?", "a palm"),
        ("What has cities but no houses, forests but no trees, and rivers but no water?", "a map"),
        ("What can you hold in your left hand but not your right?", "your right elbow"),
        ("What has many keys but can't open a single door?", "a piano"),
        ("What begins with an e, but only has one letter in it?", "an envelope"),
        ("What has a bed but never sleeps, can run but never walks?", "a river"),
        ("What is easy to get into, but hard to get out of?", "trouble"),
        ("What has one head, one foot, and four legs?", "a bed"),
        ("What can you catch, but not throw, that isn't a cold?", "your breath"),
        ("What has a ring but no finger?", "a telephone"),
        ("What starts with a t, ends with a t, and has t in it?", "a teapot"),
        ("What has a heart that doesn't beat?", "an artichoke"),
        ("The more you take, the more you leave behind. What am I?", "footsteps"),
        ("What can you break, even if you never pick it up or touch it?", "a promise"),
        ("What has many teeth but cannot bite?", "a comb"),
        ("What gets wetter as it dries?", "a towel"),
        ("I have branches, but no fruit, trunk, or leaves. What am I?", "a bank"),
        ("What is always coming but never arrives?", "tomorrow"),
        ("What has a head and a tail but no body?", "a coin"),
        ("What can you serve but never eat?", "a volleyball"),
        ("What has to be broken before you can use it?", "an egg"),
        ("I shave every day, but my beard stays the same. What am I?", "a barber"),
        ("What can you catch but not throw?", "a cold"),
        ("What kind of coat is always wet when you put it on?", "a coat of paint"),
        ("What is as big as an elephant but weighs nothing at all?", "the elephant's shadow"),
        ("What has a golden head and a golden tail but no golden body?", "a coin"),
        ("What flies without wings?", "time"),
        ("What can run but never walks, has a mouth but never talks, has a bed but never sleeps?", "a river"),
        ("What is put on a table, cut, but never eaten?", "a deck of cards"),
        ("What has many keys, but no locks; space, but no room; and you can enter, but not go in?", "a keyboard"),
        ("What is so delicate that saying its name breaks it?", "silence"),
        ("What can travel around the world while staying in a corner?", "a stamp"),
        ("The more you take away from me, the bigger I get. What am I?", "a hole"),
        ("What has many ears but cannot hear a single thing?", "a cornfield"),
        ("What is always old and sometimes new, never sad and sometimes blue, never empty and sometimes full?", "the moon"),
        ("What can you keep even after giving it away?", "your word"),
        ("What has one head, one foot, and four legs?", "a bed"),
        ("What is lighter than a feather, but even the strongest person can't hold it for more than a few minutes?", "breath"),
        ("What can be cracked, made, told, and played?", "a joke"),
        ("What has an endless supply of letters but starts empty?", "a mailbox"),
        ("What building has the most stories in the whole world?", "a library"),
        ("What has a face but cannot smile, and hands but cannot clap?", "a clock"),
        ("What can you find at the end of everything?", "the letter g"),
        ("What has many needles but doesn't sew?", "a pine tree"),
        ("What jumps when it walks and sits when it stands?", "a kangaroo"),
        ("What has one eye, yet cannot see at all?", "a needle"),
        ("What has a thumb and fingers but isn't alive?", "a glove"),
        ("What kind of band never plays music?", "a rubber band"),
        ("What has a neck and no head, two arms and no hands?", "a shirt"),
        ("What is full of holes but still holds water?", "a sponge"),
        ("What has words but never speaks, has pages but is never read aloud by itself?", "a book"),
        ("What can you hold without ever touching it?", "your breath"),
        ("What runs all around a backyard yet never moves?", "a fence"),
        ("What has a spine but no bones, and covers but isn't a bed?", "a book"),
        ("What goes up but never comes down?", "your age"),
        ("What can you break without ever touching or lifting it?", "the silence"),
        ("What has a bark but no bite, and stands in a yard?", "a tree"),
        ("What can you make that no one, not even you, can ever see?", "noise"),
        ("What has a bottom at the very top?", "your legs"),
        ("What travels the world but always stays in one corner of an envelope?", "a stamp"),
        ("What kind of cup doesn't hold water?", "a cupcake"),
        ("What has a face that changes every twelve hours but never ages?", "a clock"),
        ("What five-letter word, if you remove the first letter, still sounds exactly the same?", "queue"),
        ("What kind of tree fits in your hand?", "a palm"),
        ("What can go through glass without breaking it?", "light"),
        ("What has words but is never spoken aloud on its own?", "a letter"),
        ("What can you break with just one word?", "silence"),
        ("What has an endless number of pages but no cover?", "the internet"),
        ("What kind of key opens no lock at all?", "a monkey, or a piano key"),
        ("What goes through towns and over hills but never actually moves an inch?", "a road"),
        ("What can be as light as a whisper yet loud enough to end a debate instantly?", "the truth"),
        ("What has many rings, yet no fingers to wear them on?", "a tree trunk"),
        ("What kind of room has no walls, floor, or ceiling?", "a mushroom"),
        ("What five-letter word gets shorter no matter how many letters you add?", "short"),
        ("What can be given but kept at the very same time?", "your word"),
        ("What has a bell but makes no sound until you press it?", "a doorbell"),
        ("What kind of coat can only be put on when it's already wet?", "a coat of paint"),
        ("What can fill an entire room without taking up any space?", "light"),
        ("What has four legs in the morning, two legs at noon, and three legs in the evening?", "a human, across a lifetime"),
        ("What kind of table has no legs at all?", "a timetable"),
        ("What always stays in the corner but still travels the whole world?", "a postage stamp"),
        ("What can be cracked, played, made, and told, all without breaking anything physical?", "a joke"),
        ("What has a bottom, a top, and sides, but never any contents at all?", "a hill"),
        ("What kind of ship never sails but always has a captain?", "a friendship"),
        ("What can be measured but never actually seen or held?", "time"),
        ("What always runs but is completely unable to walk?", "water"),
        ("What has an eye but has never been able to cry a single tear?", "a needle"),
        ("What always weighs the exact same no matter how big or small it gets?", "a shadow's darkness, or a secret"),
        ("What can be folded but never actually unfolded back the same way twice?", "time"),
        ("What has legs, yet never actually walks a single step?", "a chair"),
        ("What has a bed but never actually sleeps in it?", "a river"),
        ("What kind of clock never actually needs winding?", "a sundial"),
        ("What always follows you around but is completely invisible at night?", "your shadow"),
        ("What can be shared endlessly without anyone ever having less of it?", "an idea"),
    ]

    TRIVIA = {
        "en": [
            {"question": "What is the largest planet in our solar system?",
             "choices": ["Earth", "Jupiter", "Saturn", "Mars"], "answer": "jupiter"},
            {"question": "In what year did the Titanic sink?",
             "choices": ["1905", "1912", "1918", "1923"], "answer": "1912"},
            {"question": "What is the chemical symbol for gold?",
             "choices": ["Go", "Gd", "Au", "Ag"], "answer": "au"},
            {"question": "Which programming language was created by Guido van Rossum?",
             "choices": ["Java", "Python", "Ruby", "C++"], "answer": "python"},
            {"question": "What is the smallest country in the world by area?",
             "choices": ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], "answer": "vatican city"},
            {"question": "How many continents are there on Earth?",
             "choices": ["5", "6", "7", "8"], "answer": "7"},
            {"question": "What is the longest river in the world?",
             "choices": ["Amazon", "Nile", "Yangtze", "Mississippi"], "answer": "nile"},
            {"question": "Which planet is known as the Red Planet?",
             "choices": ["Venus", "Jupiter", "Mars", "Mercury"], "answer": "mars"},
            {"question": "What does 'HTTP' stand for?",
             "choices": ["HyperText Transfer Protocol", "HighText Transfer Protocol",
                          "HyperText Translate Protocol", "HyperTransfer Text Protocol"],
             "answer": "hypertext transfer protocol"},
            {"question": "Who painted the Mona Lisa?",
             "choices": ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], "answer": "leonardo da vinci"},
            {"question": "What is the tallest mountain in the world?",
             "choices": ["K2", "Mount Everest", "Kangchenjunga", "Denali"], "answer": "mount everest"},
            {"question": "How many bones are in the adult human body?",
             "choices": ["196", "206", "216", "226"], "answer": "206"},
            {"question": "What is the capital city of Australia?",
             "choices": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": "canberra"},
            {"question": "Which element has the chemical symbol 'O'?",
             "choices": ["Osmium", "Oxygen", "Gold", "Iron"], "answer": "oxygen"},
            {"question": "In what year did the Berlin Wall fall?",
             "choices": ["1987", "1989", "1991", "1993"], "answer": "1989"},
            {"question": "What is the fastest land animal?",
             "choices": ["Lion", "Cheetah", "Pronghorn", "Gazelle"], "answer": "cheetah"},
            {"question": "Which planet has the most moons (as commonly cited)?",
             "choices": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": "saturn"},
            {"question": "What language has the most native speakers worldwide?",
             "choices": ["English", "Spanish", "Mandarin Chinese", "Hindi"], "answer": "mandarin chinese"},
            {"question": "Who wrote 'Romeo and Juliet'?",
             "choices": ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], "answer": "william shakespeare"},
            {"question": "What is the currency of Japan?",
             "choices": ["Won", "Yuan", "Yen", "Ringgit"], "answer": "yen"},
            {"question": "What gas do plants absorb from the atmosphere for photosynthesis?",
             "choices": ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], "answer": "carbon dioxide"},
            {"question": "Which ocean is the largest by area?",
             "choices": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": "pacific"},
            {"question": "Who is credited with inventing the telephone?",
             "choices": ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], "answer": "alexander graham bell"},
            {"question": "What is the hardest natural substance on Earth?",
             "choices": ["Gold", "Diamond", "Quartz", "Titanium"], "answer": "diamond"},
            {"question": "What is the smallest planet in our solar system?",
             "choices": ["Mars", "Mercury", "Venus", "Pluto"], "answer": "mercury"},
            {"question": "Who developed the theory of general relativity?",
             "choices": ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], "answer": "albert einstein"},
            {"question": "What is the largest species of shark?",
             "choices": ["Great White Shark", "Whale Shark", "Tiger Shark", "Hammerhead Shark"], "answer": "whale shark"},
            {"question": "Which country invented paper?",
             "choices": ["Egypt", "China", "Greece", "India"], "answer": "china"},
            {"question": "What is the main ingredient in traditional guacamole?",
             "choices": ["Tomato", "Avocado", "Onion", "Lime"], "answer": "avocado"},
            {"question": "How many strings does a standard violin have?",
             "choices": ["3", "4", "5", "6"], "answer": "4"},
            {"question": "What is the largest internal organ in the human body?",
             "choices": ["Heart", "Liver", "Lungs", "Kidneys"], "answer": "liver"},
            {"question": "Which country hosted the first modern Olympic Games in 1896?",
             "choices": ["France", "Italy", "Greece", "United Kingdom"], "answer": "greece"},
            {"question": "What is the freezing point of water in Fahrenheit?",
             "choices": ["0", "32", "100", "212"], "answer": "32"},
            {"question": "Which artist is known for cutting off part of his own ear?",
             "choices": ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"], "answer": "vincent van gogh"},
            {"question": "What is the largest desert in the world (including polar deserts)?",
             "choices": ["Sahara", "Arabian", "Antarctic", "Gobi"], "answer": "antarctic"},
            {"question": "Which vitamin is produced when skin is exposed to sunlight?",
             "choices": ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], "answer": "vitamin d"},
            {"question": "What is the national sport of Japan?",
             "choices": ["Judo", "Sumo wrestling", "Karate", "Baseball"], "answer": "sumo wrestling"},
            {"question": "Which two countries share the longest international border?",
             "choices": ["USA and Canada", "Russia and China", "China and India", "Brazil and Argentina"], "answer": "usa and canada"},
            {"question": "What is the study of earthquakes called?",
             "choices": ["Seismology", "Geology", "Meteorology", "Volcanology"], "answer": "seismology"},
            {"question": "Which composer wrote the 'Moonlight Sonata'?",
             "choices": ["Mozart", "Bach", "Beethoven", "Chopin"], "answer": "beethoven"},
            {"question": "What is the tallest species of penguin?",
             "choices": ["King Penguin", "Emperor Penguin", "Gentoo Penguin", "Chinstrap Penguin"], "answer": "emperor penguin"},
            {"question": "What is the SI unit of electric current?",
             "choices": ["Volt", "Watt", "Ampere", "Ohm"], "answer": "ampere"},
            {"question": "Which country is home to the ancient city of Machu Picchu?",
             "choices": ["Mexico", "Peru", "Chile", "Bolivia"], "answer": "peru"},
            {"question": "What is the largest mammal in the world?",
             "choices": ["African Elephant", "Blue Whale", "Giraffe", "Sperm Whale"], "answer": "blue whale"},
            {"question": "Which planet is known for its prominent ring system?",
             "choices": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": "saturn"},
            {"question": "What is the chemical symbol for iron?",
             "choices": ["Ir", "In", "Fe", "I"], "answer": "fe"},
            {"question": "Who wrote the novel '1984'?",
             "choices": ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], "answer": "george orwell"},
            {"question": "What is the capital city of Canada?",
             "choices": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": "ottawa"},
            {"question": "How many players are on a standard soccer team on the field?",
             "choices": ["9", "10", "11", "12"], "answer": "11"},
            {"question": "What is the main gas found in Earth's atmosphere?",
             "choices": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "answer": "nitrogen"},
        
        ],
        "sw": [
        {"question": "Ni sayari gani kubwa zaidi katika mfumo wetu wa jua?",
         "choices": ["Dunia", "Jupita", "Zohali", "Mihiri"], "answer": "jupita"},
        {"question": "Mwaka gani meli ya Titanic ilizama?",
         "choices": ["1905", "1912", "1918", "1923"], "answer": "1912"},
        {"question": "Ni alama gani ya kemikali ya dhahabu?",
         "choices": ["Go", "Gd", "Au", "Ag"], "answer": "au"},
        {"question": "Ni lugha gani ya kompyuta iliyoundwa na Guido van Rossum?",
         "choices": ["Java", "Python", "Ruby", "C++"], "answer": "python"},
        {"question": "Ni nchi gani ndogo zaidi duniani kwa eneo?",
         "choices": ["Monaco", "San Marino", "Jiji la Vatikani", "Liechtenstein"], "answer": "jiji la vatikani"},
        {"question": "Kuna mabara mangapi duniani?",
         "choices": ["5", "6", "7", "8"], "answer": "7"},
        {"question": "Ni mto gani mrefu zaidi duniani?",
         "choices": ["Amazoni", "Naili", "Yangtze", "Mississippi"], "answer": "naili"},
        {"question": "Ni sayari gani inajulikana kama 'Sayari Nyekundu'?",
         "choices": ["Zuhura", "Jupita", "Mihiri", "Utaridi"], "answer": "mihiri"},
        {"question": "'HTTP' inasimamia nini?",
         "choices": ["HyperText Transfer Protocol", "HighText Transfer Protocol", "HyperText Translate Protocol", "HyperTransfer Text Protocol"], "answer": "hypertext transfer protocol"},
        {"question": "Ni nani aliyechora picha ya Mona Lisa?",
         "choices": ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], "answer": "leonardo da vinci"},
        {"question": "Ni mlima gani mrefu zaidi duniani?",
         "choices": ["K2", "Mlima Everest", "Kangchenjunga", "Denali"], "answer": "mlima everest"},
        {"question": "Mifupa mingapi iko katika mwili wa mtu mzima?",
         "choices": ["196", "206", "216", "226"], "answer": "206"},
        {"question": "Mji mkuu wa Australia ni upi?",
         "choices": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": "canberra"},
        {"question": "Ni kipengele gani chenye alama ya kemikali 'O'?",
         "choices": ["Osmium", "Oksijeni", "Dhahabu", "Chuma"], "answer": "oksijeni"},
        {"question": "Mwaka gani Ukuta wa Berlin ulianguka?",
         "choices": ["1987", "1989", "1991", "1993"], "answer": "1989"},
        {"question": "Ni mnyama gani wa nchi kavu mwepesi zaidi?",
         "choices": ["Simba", "Duma", "Pronghorn", "Swala"], "answer": "duma"},
        {"question": "Ni sayari gani yenye miezi mingi zaidi (kwa mujibu wa takwimu za kawaida)?",
         "choices": ["Jupita", "Zohali", "Uranus", "Neptune"], "answer": "zohali"},
        {"question": "Ni lugha gani ina wazungumzaji wa asili wengi zaidi duniani?",
         "choices": ["Kiingereza", "Kihispania", "Kimandarini cha China", "Kihindi"], "answer": "kimandarini cha china"},
        {"question": "Ni nani aliyeandika 'Romeo and Juliet'?",
         "choices": ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], "answer": "william shakespeare"},
        {"question": "Sarafu ya Japani ni ipi?",
         "choices": ["Won", "Yuan", "Yen", "Ringgit"], "answer": "yen"},
        {"question": "Ni gesi gani mimea huvuta kutoka hewani kwa ajili ya usanisinuru?",
         "choices": ["Oksijeni", "Naitrojeni", "Kaboni dioksidi", "Haidrojeni"], "answer": "kaboni dioksidi"},
        {"question": "Ni bahari gani kubwa zaidi kwa eneo?",
         "choices": ["Atlantiki", "Hindi", "Aktiki", "Pasifiki"], "answer": "pasifiki"},
        {"question": "Ni nani anayesifiwa kwa uvumbuzi wa simu?",
         "choices": ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], "answer": "alexander graham bell"},
        {"question": "Ni dutu gani ngumu zaidi ya asili duniani?",
         "choices": ["Dhahabu", "Almasi", "Kwatzi", "Titani"], "answer": "almasi"},
        {"question": "Ni sayari gani ndogo zaidi katika mfumo wetu wa jua?",
         "choices": ["Mihiri", "Utaridi", "Zuhura", "Pluto"], "answer": "utaridi"},
        {"question": "Ni nani aliyeasisi nadharia ya uhusiano wa jumla?",
         "choices": ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], "answer": "albert einstein"},
        {"question": "Ni aina gani ya papa kubwa zaidi?",
         "choices": ["Papa Mweupe Mkubwa", "Papa Nyangumi", "Papa Chui", "Papa Nyundo"], "answer": "papa nyangumi"},
        {"question": "Ni nchi gani iliyovumbua karatasi?",
         "choices": ["Misri", "China", "Ugiriki", "India"], "answer": "china"},
        {"question": "Ni kiungo gani kikuu cha guacamole ya asili?",
         "choices": ["Nyanya", "Parachichi", "Kitunguu", "Ndimu"], "answer": "parachichi"},
        {"question": "Violin ya kawaida ina nyuzi ngapi?",
         "choices": ["3", "4", "5", "6"], "answer": "4"},
        {"question": "Ni kiungo gani cha ndani kikubwa zaidi mwilini mwa binadamu?",
         "choices": ["Moyo", "Ini", "Mapafu", "Figo"], "answer": "ini"},
        {"question": "Ni nchi gani iliyoandaa Michezo ya kwanza ya Olimpiki za kisasa mwaka 1896?",
         "choices": ["Ufaransa", "Italia", "Ugiriki", "Uingereza"], "answer": "ugiriki"},
        {"question": "Maji huganda kwenye nyuzi joto ngapi za Fahrenheit?",
         "choices": ["0", "32", "100", "212"], "answer": "32"},
        {"question": "Ni msanii gani anayejulikana kwa kukata sehemu ya sikio lake mwenyewe?",
         "choices": ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"], "answer": "vincent van gogh"},
        {"question": "Ni jangwa gani kubwa zaidi duniani (likijumuisha majangwa ya barafu)?",
         "choices": ["Sahara", "Arabia", "Antaktika", "Gobi"], "answer": "antaktika"},
        {"question": "Ni vitamini gani huzalishwa ngozi inapopigwa na jua?",
         "choices": ["Vitamini A", "Vitamini C", "Vitamini D", "Vitamini K"], "answer": "vitamini d"},
        {"question": "Ni mchezo gani wa taifa wa Japani?",
         "choices": ["Judo", "Mieleka wa Sumo", "Karate", "Besiboli"], "answer": "mieleka wa sumo"},
        {"question": "Ni nchi gani mbili zenye mpaka mrefu zaidi duniani?",
         "choices": ["Marekani na Kanada", "Urusi na China", "China na India", "Brazili na Argentina"], "answer": "marekani na kanada"},
        {"question": "Ni nini jina la taaluma ya kusoma matetemeko ya ardhi?",
         "choices": ["Seismolojia", "Jiolojia", "Hali ya hewa", "Volkenolojia"], "answer": "seismolojia"},
        {"question": "Ni mtunzi gani aliyetunga 'Moonlight Sonata'?",
         "choices": ["Mozart", "Bach", "Beethoven", "Chopin"], "answer": "beethoven"},
        {"question": "Ni aina gani ya pengwini mrefu zaidi?",
         "choices": ["Pengwini Mfalme", "Pengwini Kaisari", "Pengwini wa Gentoo", "Pengwini wa Chinstrap"], "answer": "pengwini kaisari"},
        {"question": "Ni kipimo gani cha SI cha mkondo wa umeme?",
         "choices": ["Volti", "Wati", "Ampea", "Ohm"], "answer": "ampea"},
        {"question": "Ni nchi gani nyumbani kwa mji wa kale wa Machu Picchu?",
         "choices": ["Meksiko", "Peru", "Chile", "Bolivia"], "answer": "peru"},
        {"question": "Ni mnyama gani mkubwa zaidi duniani?",
         "choices": ["Tembo wa Afrika", "Nyangumi wa Bluu", "Twiga", "Nyangumi wa Manii"], "answer": "nyangumi wa bluu"},
        {"question": "Ni sayari gani inajulikana kwa mfumo wake mkubwa wa pete?",
         "choices": ["Jupita", "Zohali", "Uranus", "Neptune"], "answer": "zohali"},
        {"question": "Ni alama gani ya kemikali ya chuma (iron)?",
         "choices": ["Ir", "In", "Fe", "I"], "answer": "fe"},
        {"question": "Ni nani aliyeandika riwaya '1984'?",
         "choices": ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], "answer": "george orwell"},
        {"question": "Mji mkuu wa Kanada ni upi?",
         "choices": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": "ottawa"},
        {"question": "Ni wachezaji wangapi wako uwanjani kwa timu moja ya kawaida ya soka?",
         "choices": ["9", "10", "11", "12"], "answer": "11"},
        {"question": "Ni gesi gani kuu inayopatikana katika angahewa la Dunia?",
         "choices": ["Oksijeni", "Kaboni dioksidi", "Naitrojeni", "Haidrojeni"], "answer": "naitrojeni"},
        ],
        "fr": [
        {"question": "Quelle est la plus grande planète de notre système solaire ?",
         "choices": ["Terre", "Jupiter", "Saturne", "Mars"], "answer": "jupiter"},
        {"question": "En quelle année le Titanic a-t-il coulé ?",
         "choices": ["1905", "1912", "1918", "1923"], "answer": "1912"},
        {"question": "Quel est le symbole chimique de l'or ?",
         "choices": ["Go", "Gd", "Au", "Ag"], "answer": "au"},
        {"question": "Quel langage de programmation a été créé par Guido van Rossum ?",
         "choices": ["Java", "Python", "Ruby", "C++"], "answer": "python"},
        {"question": "Quel est le plus petit pays du monde en superficie ?",
         "choices": ["Monaco", "Saint-Marin", "Cité du Vatican", "Liechtenstein"], "answer": "cité du vatican"},
        {"question": "Combien y a-t-il de continents sur Terre ?",
         "choices": ["5", "6", "7", "8"], "answer": "7"},
        {"question": "Quel est le plus long fleuve du monde ?",
         "choices": ["Amazone", "Nil", "Yangtsé", "Mississippi"], "answer": "nil"},
        {"question": "Quelle planète est connue sous le nom de 'planète rouge' ?",
         "choices": ["Vénus", "Jupiter", "Mars", "Mercure"], "answer": "mars"},
        {"question": "Que signifie 'HTTP' ?",
         "choices": ["HyperText Transfer Protocol", "HighText Transfer Protocol", "HyperText Translate Protocol", "HyperTransfer Text Protocol"], "answer": "hypertext transfer protocol"},
        {"question": "Qui a peint la Joconde (Mona Lisa) ?",
         "choices": ["Michel-Ange", "Raphaël", "Léonard de Vinci", "Donatello"], "answer": "léonard de vinci"},
        {"question": "Quelle est la plus haute montagne du monde ?",
         "choices": ["K2", "Mont Everest", "Kangchenjunga", "Denali"], "answer": "mont everest"},
        {"question": "Combien d'os y a-t-il dans le corps d'un adulte ?",
         "choices": ["196", "206", "216", "226"], "answer": "206"},
        {"question": "Quelle est la capitale de l'Australie ?",
         "choices": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": "canberra"},
        {"question": "Quel élément a le symbole chimique 'O' ?",
         "choices": ["Osmium", "Oxygène", "Or", "Fer"], "answer": "oxygène"},
        {"question": "En quelle année le mur de Berlin est-il tombé ?",
         "choices": ["1987", "1989", "1991", "1993"], "answer": "1989"},
        {"question": "Quel est l'animal terrestre le plus rapide ?",
         "choices": ["Lion", "Guépard", "Antilope d'Amérique", "Gazelle"], "answer": "guépard"},
        {"question": "Quelle planète a le plus de lunes (selon les décomptes courants) ?",
         "choices": ["Jupiter", "Saturne", "Uranus", "Neptune"], "answer": "saturne"},
        {"question": "Quelle langue compte le plus de locuteurs natifs dans le monde ?",
         "choices": ["Anglais", "Espagnol", "Mandarin", "Hindi"], "answer": "mandarin"},
        {"question": "Qui a écrit 'Roméo et Juliette' ?",
         "choices": ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], "answer": "william shakespeare"},
        {"question": "Quelle est la monnaie du Japon ?",
         "choices": ["Won", "Yuan", "Yen", "Ringgit"], "answer": "yen"},
        {"question": "Quel gaz les plantes absorbent-elles pour la photosynthèse ?",
         "choices": ["Oxygène", "Azote", "Dioxyde de carbone", "Hydrogène"], "answer": "dioxyde de carbone"},
        {"question": "Quel est le plus grand océan par superficie ?",
         "choices": ["Atlantique", "Indien", "Arctique", "Pacifique"], "answer": "pacifique"},
        {"question": "Qui est crédité de l'invention du téléphone ?",
         "choices": ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], "answer": "alexander graham bell"},
        {"question": "Quelle est la substance naturelle la plus dure sur Terre ?",
         "choices": ["Or", "Diamant", "Quartz", "Titane"], "answer": "diamant"},
        {"question": "Quelle est la plus petite planète de notre système solaire ?",
         "choices": ["Mars", "Mercure", "Vénus", "Pluton"], "answer": "mercure"},
        {"question": "Qui a développé la théorie de la relativité générale ?",
         "choices": ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], "answer": "albert einstein"},
        {"question": "Quelle est la plus grande espèce de requin ?",
         "choices": ["Grand requin blanc", "Requin-baleine", "Requin tigre", "Requin-marteau"], "answer": "requin-baleine"},
        {"question": "Quel pays a inventé le papier ?",
         "choices": ["Égypte", "Chine", "Grèce", "Inde"], "answer": "chine"},
        {"question": "Quel est l'ingrédient principal du guacamole traditionnel ?",
         "choices": ["Tomate", "Avocat", "Oignon", "Citron vert"], "answer": "avocat"},
        {"question": "Combien de cordes a un violon standard ?",
         "choices": ["3", "4", "5", "6"], "answer": "4"},
        {"question": "Quel est le plus grand organe interne du corps humain ?",
         "choices": ["Cœur", "Foie", "Poumons", "Reins"], "answer": "foie"},
        {"question": "Quel pays a accueilli les premiers Jeux olympiques modernes en 1896 ?",
         "choices": ["France", "Italie", "Grèce", "Royaume-Uni"], "answer": "grèce"},
        {"question": "Quel est le point de congélation de l'eau en degrés Fahrenheit ?",
         "choices": ["0", "32", "100", "212"], "answer": "32"},
        {"question": "Quel artiste est connu pour s'être coupé une partie de l'oreille ?",
         "choices": ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"], "answer": "vincent van gogh"},
        {"question": "Quel est le plus grand désert du monde (déserts polaires inclus) ?",
         "choices": ["Sahara", "Arabie", "Antarctique", "Gobi"], "answer": "antarctique"},
        {"question": "Quelle vitamine est produite lorsque la peau est exposée au soleil ?",
         "choices": ["Vitamine A", "Vitamine C", "Vitamine D", "Vitamine K"], "answer": "vitamine d"},
        {"question": "Quel est le sport national du Japon ?",
         "choices": ["Judo", "Lutte sumo", "Karaté", "Baseball"], "answer": "lutte sumo"},
        {"question": "Quels deux pays partagent la plus longue frontière internationale ?",
         "choices": ["États-Unis et Canada", "Russie et Chine", "Chine et Inde", "Brésil et Argentine"], "answer": "états-unis et canada"},
        {"question": "Comment appelle-t-on l'étude des tremblements de terre ?",
         "choices": ["Sismologie", "Géologie", "Météorologie", "Volcanologie"], "answer": "sismologie"},
        {"question": "Quel compositeur a écrit la 'Sonate au clair de lune' ?",
         "choices": ["Mozart", "Bach", "Beethoven", "Chopin"], "answer": "beethoven"},
        {"question": "Quelle est la plus grande espèce de manchot ?",
         "choices": ["Manchot royal", "Manchot empereur", "Manchot papou", "Manchot à jugulaire"], "answer": "manchot empereur"},
        {"question": "Quelle est l'unité SI du courant électrique ?",
         "choices": ["Volt", "Watt", "Ampère", "Ohm"], "answer": "ampère"},
        {"question": "Quel pays abrite l'ancienne cité du Machu Picchu ?",
         "choices": ["Mexique", "Pérou", "Chili", "Bolivie"], "answer": "pérou"},
        {"question": "Quel est le plus grand mammifère du monde ?",
         "choices": ["Éléphant d'Afrique", "Baleine bleue", "Girafe", "Cachalot"], "answer": "baleine bleue"},
        {"question": "Quelle planète est connue pour son système d'anneaux proéminent ?",
         "choices": ["Jupiter", "Saturne", "Uranus", "Neptune"], "answer": "saturne"},
        {"question": "Quel est le symbole chimique du fer ?",
         "choices": ["Ir", "In", "Fe", "I"], "answer": "fe"},
        {"question": "Qui a écrit le roman '1984' ?",
         "choices": ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], "answer": "george orwell"},
        {"question": "Quelle est la capitale du Canada ?",
         "choices": ["Toronto", "Vancouver", "Ottawa", "Montréal"], "answer": "ottawa"},
        {"question": "Combien de joueurs une équipe de football standard a-t-elle sur le terrain ?",
         "choices": ["9", "10", "11", "12"], "answer": "11"},
        {"question": "Quel est le principal gaz présent dans l'atmosphère terrestre ?",
         "choices": ["Oxygène", "Dioxyde de carbone", "Azote", "Hydrogène"], "answer": "azote"},
        ],
    }

    def __init__(self):
        self._last_riddle_answer = None
        self._last_trivia = None

    def random_joke(self, lang: str = "en") -> str:
        pool = self.JOKES.get(lang) or self.JOKES["en"]
        setup, punchline = random.choice(pool)
        return f"{setup}\n...{punchline}"

    def random_quote(self) -> str:
        text, author = random.choice(self.QUOTES)
        return f'"{text}"\n— {author}'

    def random_riddle(self) -> str:
        riddle, answer = random.choice(self.RIDDLES)
        self._last_riddle_answer = answer
        return riddle

    def reveal_riddle_answer(self) -> str:
        if self._last_riddle_answer is None:
            return "I haven't given you a riddle yet this session - ask for one first!"
        answer = self._last_riddle_answer
        self._last_riddle_answer = None
        return f"The answer was: {answer}"

    def check_riddle_guess(self, guess: str):
        """Returns (is_correct: bool, answer: str) or None if no active riddle."""
        if self._last_riddle_answer is None:
            return None
        answer = self._last_riddle_answer
        guess_clean = re.sub(r"[^a-z0-9\s]", "", guess.lower()).strip()
        answer_clean = re.sub(r"[^a-z0-9\s]", "", answer.lower()).strip()
        is_correct = guess_clean == answer_clean or answer_clean in guess_clean
        if is_correct:
            self._last_riddle_answer = None
        return is_correct, answer

    def random_trivia(self, lang: str = "en") -> str:
        pool = self.TRIVIA.get(lang) or self.TRIVIA["en"]
        item = random.choice(pool)
        self._last_trivia = item
        lines = [item["question"]]
        letters = ["A", "B", "C", "D"]
        for letter, choice in zip(letters, item["choices"]):
            lines.append(f"  {letter}) {choice}")
        return "\n".join(lines)

    def check_trivia_guess(self, guess: str):
        """Returns (is_correct: bool, correct_answer_display: str) or None
        if there's no active trivia question to check against."""
        if self._last_trivia is None:
            return None
        item = self._last_trivia
        answer = item["answer"]
        guess_clean = guess.lower().strip().rstrip(".!?")

        # Allow answering with the letter (A/B/C/D) or the full answer text.
        letters = ["a", "b", "c", "d"]
        if guess_clean in letters:
            idx = letters.index(guess_clean)
            if idx < len(item["choices"]):
                guess_clean = item["choices"][idx].lower()

        is_correct = guess_clean == answer.lower() or answer.lower() in guess_clean

        # Find the properly-capitalized version of the answer for display.
        display_answer = answer
        for choice in item["choices"]:
            if choice.lower() == answer.lower():
                display_answer = choice
                break

        if is_correct:
            self._last_trivia = None
        return is_correct, display_answer


# ==============================================================================
